apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demo-tls
  namespace: demo-ns
spec:
  secretName: demo-tls
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  dnsNames:
    - demo.local
